keys:
  - &laptop age1hw637g2a3kerd7jaqncxznrx67yeyfzyqg7cpwy3mekw9tsjt48sarxqn7
  - &work-macos age1u3mlmjlfsaa589qqzxjwk5e3ej04eqqlfyhumvfuude70aj9945svms6ha
creation_rules:
  - path_regex: hosts/laptop/secrets/.+$
    key_groups:
      - age:
          - *laptop
  - path_regex: hosts/work-macos/secrets/.+$
    key_groups:
      - age:
          - *work-macos
