keys:
  - &desktop age16wwdta66lx3tzsk9f56arlmf8gx9e5zktxl3vs50dawyg9ctr9ws2c85ng
  - &bphenriques age160xsly2d84lz89vzhkussw3pth2fhkstx03cd7uc5df6zdpsfvnsktf7hs
creation_rules:
  - path_regex: host/desktop/secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *desktop
  - path_regex: host/laptop/secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *bphenriques
