keys:
  - &laptop-system age1hw637g2a3kerd7jaqncxznrx67yeyfzyqg7cpwy3mekw9tsjt48sarxqn7
creation_rules:
  - path_regex: hosts/laptop/secrets.yaml
    key_groups:
      - age: [ *laptop-system ]
  - path_regex: hosts/compute/secrets.yaml
    key_groups:
      - age: [ *laptop-system ]
