tap "homebrew/cask"

# Internet
cask "firefox"

# Secret management
cask "keybase"

# Containers
cask "docker"

# IntelliJ and cousins
cask "jetbrains-toolbox"

# Window manager (no tiling WM for now)
cask "rectangle"

