# Window Settings
window:
  startup_mode: Maximized

# Font configuration (changes require restart)
font:
  size: 13.0
  normal:
    family: Hack Nerd Font Mono
    style: Regular
  bold:
    family: Hack Nerd Font Mono
    style: Bold
  italic:
    family: Hack Nerd Font Mono
    style: Italic

# Theme inspired by Doom One: https://github.com/hlissner/emacs-doom-themes
colors:
  # Default colors
  primary:
    background: '0x282c34'
    foreground: '0xbbc2cf'

  # Normal colors
  normal:
    black:   '0x282c34'
    red:     '0xff6c6b'
    green:   '0x98be65'
    yellow:  '0xecbe7b'
    blue:    '0x51afef'
    magenta: '0xc678dd'
    cyan:    '0x46d9ff'
    white:   '0xbbc2cf'

# Fix characters not being inserted when using Alt in MacOS.
alt_send_esc: false

# Shortcuts
key_bindings:
  # General Alacritty key bindings
  - { key: Space,       mods: Alt,            chars: " "                }
  - { key: Left,        mods: Alt,            chars: "\x1bb"            } # one word left
  - { key: Right,       mods: Alt,            chars: "\x1bf"            } # one word right

  # Fixes lack of proper bindings. See
  # - https://github.com/alacritty/alacritty/issues/2017
  # - https://github.com/alacritty/alacritty/issues/623
  # - https://github.com/alacritty/alacritty/issues/62
  - { key: A,           mods: Alt,             chars: "\x1Ba"           }
  - { key: A,           mods: Alt|Shift,       chars: "\x1BA"           }
  - { key: B,           mods: Alt,             chars: "\x1Bb"           }
  - { key: B,           mods: Alt|Shift,       chars: "\x1BB"           }
  - { key: C,           mods: Alt,             chars: "\x1Bc"           }
  - { key: C,           mods: Alt|Shift,       chars: "\x1BC"           }
  - { key: D,           mods: Alt,             chars: "\x1Bd"           }
  - { key: D,           mods: Alt|Shift,       chars: "\x1BD"           }
  - { key: E,           mods: Alt,             chars: "\x1Be"           }
  - { key: E,           mods: Alt|Shift,       chars: "\x1BE"           }
  - { key: F,           mods: Alt,             chars: "\x1Bf"           }
  - { key: F,           mods: Alt|Shift,       chars: "\x1BF"           }
  - { key: G,           mods: Alt,             chars: "\x1Bg"           }
  - { key: G,           mods: Alt|Shift,       chars: "\x1BG"           }
  - { key: H,           mods: Alt,             chars: "\x1Bh"           }
  - { key: H,           mods: Alt|Shift,       chars: "\x1BH"           }
  - { key: I,           mods: Alt,             chars: "\x1Bi"           }
  - { key: I,           mods: Alt|Shift,       chars: "\x1BI"           }
  - { key: J,           mods: Alt,             chars: "\x1Bj"           }
  - { key: J,           mods: Alt|Shift,       chars: "\x1BJ"           }
  - { key: K,           mods: Alt,             chars: "\x1Bk"           }
  - { key: K,           mods: Alt|Shift,       chars: "\x1BK"           }
  - { key: L,           mods: Alt,             chars: "\x1Bl"           }
  - { key: L,           mods: Alt|Shift,       chars: "\x1BL"           }
  - { key: M,           mods: Alt,             chars: "\x1Bm"           }
  - { key: M,           mods: Alt|Shift,       chars: "\x1BM"           }
  - { key: N,           mods: Alt,             chars: "\x1Bn"           }
  - { key: N,           mods: Alt|Shift,       chars: "\x1BN"           }
  - { key: O,           mods: Alt,             chars: "\x1Bo"           }
  - { key: O,           mods: Alt|Shift,       chars: "\x1BO"           }
  - { key: P,           mods: Alt,             chars: "\x1Bp"           }
  - { key: P,           mods: Alt|Shift,       chars: "\x1BP"           }
  - { key: Q,           mods: Alt,             chars: "\x1Bq"           }
  - { key: Q,           mods: Alt|Shift,       chars: "\x1BQ"           }
  - { key: R,           mods: Alt,             chars: "\x1Br"           }
  - { key: R,           mods: Alt|Shift,       chars: "\x1BR"           }
  - { key: S,           mods: Alt,             chars: "\x1Bs"           }
  - { key: S,           mods: Alt|Shift,       chars: "\x1BS"           }
  - { key: T,           mods: Alt,             chars: "\x1Bt"           }
  - { key: T,           mods: Alt|Shift,       chars: "\x1BT"           }
  - { key: U,           mods: Alt,             chars: "\x1Bu"           }
  - { key: U,           mods: Alt|Shift,       chars: "\x1BU"           }
  - { key: V,           mods: Alt,             chars: "\x1Bv"           }
  - { key: V,           mods: Alt|Shift,       chars: "\x1BV"           }
  - { key: W,           mods: Alt,             chars: "\x1Bw"           }
  - { key: W,           mods: Alt|Shift,       chars: "\x1BW"           }
  - { key: X,           mods: Alt,             chars: "\x1Bx"           }
  - { key: X,           mods: Alt|Shift,       chars: "\x1BX"           }
  - { key: Y,           mods: Alt,             chars: "\x1By"           }
  - { key: Y,           mods: Alt|Shift,       chars: "\x1BY"           }
  - { key: Z,           mods: Alt,             chars: "\x1Bz"           }
  - { key: Z,           mods: Alt|Shift,       chars: "\x1BZ"           }
  # Worst thing about alacritty... Having to hack around the keyboard keys which is not portable at all.
  - { key: Key1,        mods: Alt,             chars: ""           }
  - { key: Key1,        mods: Alt|Shift,       chars: "¡"           }
  - { key: Key2,        mods: Alt,             chars: "@"           }
  - { key: Key2,        mods: Alt|Shift,       chars: "ﬁ"           }
  - { key: Key3,        mods: Alt,             chars: "€"           }
  - { key: Key3,        mods: Alt|Shift,       chars: "ﬂ"           }
  - { key: Key4,        mods: Alt,             chars: "£"           }
  - { key: Key4,        mods: Alt|Shift,       chars: "¢"           }
  - { key: Key5,        mods: Alt,             chars: "‰"           }
  - { key: Key5,        mods: Alt|Shift,       chars: "∞"           }
  - { key: Key6,        mods: Alt,             chars: "¶"           }
  - { key: Key6,        mods: Alt|Shift,       chars: "•"           }
  - { key: Key7,        mods: Alt,             chars: "÷"           }
  - { key: Key7,        mods: Alt|Shift,       chars: "⁄"           }
  - { key: Key8,        mods: Alt,             chars: "["           }
  - { key: Key8,        mods: Alt|Shift,       chars: "{"           }
  - { key: Key9,        mods: Alt,             chars: "]"           }
  - { key: Key9,        mods: Alt|Shift,       chars: "}"           }
  - { key: Key0,        mods: Alt,             chars: "≠"           }
  - { key: Key0,        mods: Alt|Shift,       chars: "≈"           }
