# Window Settings
window:
  startup_mode: Maximized

# Font configuration (changes require restart)
font:
  size: 13.0
  normal:
    family: Hack Nerd Font Mono
    style: Regular
  bold:
    family: Hack Nerd Font Mono
    style: Bold
  italic:
    family: Hack Nerd Font Mono
    style: Italic

# Colors (Doom One): https://github.com/hlissner/emacs-doom-themes
# Nice Themes:
#  - https://github.com/eendroroy/alacritty-theme
#  - https://github.com/sindresorhus/hyper-snazzy
colors:
  # Default colors
  primary:
    background: '0x282c34'
    foreground: '0xbbc2cf'

  # Normal colors
  normal:
    black:   '0x282c34'
    red:     '0xff6c6b'
    green:   '0x98be65'
    yellow:  '0xecbe7b'
    blue:    '0x51afef'
    magenta: '0xc678dd'
    cyan:    '0x46d9ff'
    white:   '0xbbc2cf'

# Fix characters not being inserted when using Alt in MacOS.
alt_send_esc: false

# Shortcuts
key_bindings:
  # General Alacritty key bindings
  - { key: Space,       mods: Alt,            chars: " "                 }  

