# personal-agent — guest-side NixOS configuration for the assistant microvm.
# Runs the assistant runtime (currently hermes-agent) as a service user with
# no shell or sudo. Human admin access is via the `bphenriques` account,
# reachable over SSH (ProxyJump through compute) on the bridge IP.
{ config, inputs, self, private, ... }:
let
  fleet = import ../shared.nix;
in
{
  imports = [
    inputs.microvm.nixosModules.microvm
    # mkMicrovmGuest deliberately doesn't load all self.nixosModules
    # (would pull in homelab too); pick what we need explicitly.
    self.nixosModules.ai-hermes-agent   # pulls in inputs.hermes-agent transitively
    self.nixosModules.fleet-shared      # `custom.fleet.*` options
    ./microvm.nix
    ./vault.nix
  ];

  networking.hostName = "personal-agent";
  system.stateVersion = "26.05";

  custom.fleet = import ../shared.nix;

  time.timeZone = "Europe/Lisbon";
  i18n.defaultLocale = "en_US.UTF-8";
  console.keyMap = "pt-latin1";

  # SSH is for the human admin (bphenriques), not for the agent. Reachable only
  # via ProxyJump through compute. Host keys persist on the volume so the
  # laptop's known_hosts survives rebuilds.
  services.openssh = {
    enable = true;
    settings = {
      PasswordAuthentication = false;
      PermitRootLogin = "no";
    };
    hostKeys = [
      { path = "/var/lib/hermes/.ssh-host-keys/ssh_host_ed25519_key"; type = "ed25519"; }
    ];
  };

  # Only bphenriques can perform rootful operations. The hermes service user
  # (created by the upstream module) stays minimal — no shell, sudo, or SSH.
  # Passwordless sudo is acceptable: SSH is key-only and the VM is unreachable
  # from outside compute's bridge. All hermes CLI work goes through
  # `sudo -u hermes hermes …` — read AND write paths are uniform that way.
  users.users.bphenriques = {
    isNormalUser = true;
    extraGroups = [ "wheel" "systemd-journal" ];
    openssh.authorizedKeys.keys = fleet.authorizedSSHKeys;
  };
  security.sudo.wheelNeedsPassword = false;

  # Hermes runtime. Traefik routing lives on compute (services/hermes-api.nix);
  # the VM exposes the raw OpenAI-compatible API. Model defaults to fleet
  # config; vaultPath comes from ./vault.nix.
  custom.ai.hermes-agent = {
    enable = true;
    ollamaUrl = "http://${fleet.lan.hosts.laptop}:11434/v1";
    apiKeyFile = config.sops.templates."hermes-env".path;
    soul = builtins.readFile ./SOUL.md;
  };

  # Additional Hermes backend: compute_q on compute (gemma4:e2b, CPU-only,
  # always-available). Routable as `custom:compute_q/gemma4:e2b`. Voice
  # memo workers probe the laptop and fall to compute_q silently when off;
  # NextChat exposes both in the dropdown. The AI module owns model.default
  # (laptop); we extend `settings.custom_providers` here via Hermes' free-form
  # deep-merged settings.
  services.hermes-agent.settings.custom_providers = [
    {
      name = "compute_q";
      base_url = "http://${fleet.microvm.bridge.gateway}:11434/v1";
      api_key = "ollama";
      default_model = "gemma4:e2b";
      models = [ "gemma4:e2b" ];
      context_length = config.custom.fleet.ai.contextLength;
    }
  ];

  # ntfy platform. All credentials/topology come from env (NTFY_* below);
  # this block just flips the plugin on so `hermes status` lists it and the
  # cron scheduler treats it as the home channel for `--deliver` defaults.
  services.hermes-agent.settings.platforms.ntfy.enabled = true;

  # sops activation runs in initrd, but /var/lib/hermes (where the SSH host key
  # sops uses as its age identity lives) isn't mounted yet. Re-run activation
  # in stage 2 once local-fs is up; activation is idempotent.
  systemd.services.sops-late-activate = {
    description = "Re-run NixOS activation in stage 2 so sops can decrypt off the SSH host key on /var/lib/hermes";
    wantedBy = [ "multi-user.target" ];
    before = [ "vault-sync.service" "hermes-agent.service" ];
    unitConfig.ConditionPathExists = "/var/lib/hermes/.ssh-host-keys/ssh_host_ed25519_key";
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStart = "/run/current-system/activate";
    };
  };

  # sops-nix uses the VM's ed25519 SSH host key as the age identity
  # (sops-nix converts ssh-ed25519 → age automatically). Same key as SSH login.
  sops = {
    defaultSopsFile = private.sopsSecretsFile;
    age.sshKeyPaths = [ "/var/lib/hermes/.ssh-host-keys/ssh_host_ed25519_key" ];
    secrets."hermes-agent/api-server-key" = { };
    # ntfy publisher token. Generated by ntfy-configure on compute at
    # /var/lib/homelab-secrets/ntfy-publishers/hermes-api; one-time copy:
    #   ssh compute sudo cat /var/lib/homelab-secrets/ntfy-publishers/hermes-api
    # then sops-edit dotfiles-private's personal-agent file and paste under
    # `hermes-agent/ntfy-publisher-token`.
    secrets."hermes-agent/ntfy-publisher-token" = { };
    templates."hermes-env" = {
      content = ''
        API_SERVER_ENABLED=true
        API_SERVER_PORT=8642
        API_SERVER_HOST=0.0.0.0
        API_SERVER_KEY=${config.sops.placeholder."hermes-agent/api-server-key"}

        # ntfy adapter. HTTPS via Traefik on compute — DNS resolves
        # ntfy.<domain> to compute's LAN IP; the VM reaches it via NAT through
        # compute (bridge gateway → bond0 → local delivery to Traefik on
        # 0.0.0.0:443). No /etc/hosts override needed. Subscribe topic is
        # split from publish so the bearer scope on each direction is single-
        # purpose.
        NTFY_SERVER_URL=https://ntfy.${private.settings.domain}
        NTFY_TOPIC=personal-agent-inbox
        NTFY_PUBLISH_TOPIC=personal-agent
        NTFY_HOME_CHANNEL=personal-agent
        NTFY_HOME_CHANNEL_NAME=Personal Agent
        NTFY_MARKDOWN=true
        NTFY_TOKEN=${config.sops.placeholder."hermes-agent/ntfy-publisher-token"}
      '';
      owner = "hermes";
      mode = "0400";
    };
  };
}
