tap "homebrew/cask"

# Search
brew "ripgrep"

# Json Processor
brew "jq"

# Fuzzy Search
brew "fzf"

# Better alternative to cat
brew "bat"

# Publish/Subscribe broker events
tap "batchcorp/public"
brew "plumber"

# Network
cask "ngrok"
