theme = "onedark"

[editor]
bufferline = "multiple"
color-modes = true
insert-final-newline = true
line-number = "absolute"
rulers = [120]
text-width = 120
auto-format	= false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
display-inlay-hints = true
display-messages = true
enable = true

[editor.statusline]
right = ["diagnostics", "selections", "register", "position", "file-encoding", "version-control"]

[editor.indent-guides]
render = true
character = "┊"

[keys.normal]
C-j = "save_selection"
C-s = ":w"
esc = ["collapse_selection", "keep_primary_selection"]

[keys.normal.space]
q = ":q"
space = "file_picker"
w = ":w"
