[[language]]
name = "rust"
auto-format = false

[[language]]
name = "scala"
auto-format = false

[language-server.ltex-ls] 
command = "ltex-ls"
config = { ltex = { language = "en-GB" } } # https://valentjn.github.io/ltex/settings.html

[[language]]
name = "markdown"
language-servers = ["marksman", "ltex-ls"]
