. "$ZDOTDIR/config.zsh"    # Load ZSH and Interactive Shell Configuration.
. "$ZDOTDIR/plugins.zsh"   # Load Plugins.

# Load Functions - Lazy autoload every file under $ZDOTDIR/functions
fpath=("$ZDOTDIR/functions" $fpath);
autoload -Uz $fpath[1]/*(.:t)

# Load Application specific modules
for module in $ZDOTDIR/modules/*.zsh; do
  . $module
done

. "$ZDOTDIR/aliases.zsh"                         # Load Aliases.
. "$ZDOTDIR/auto-completions.zsh"                # Load Auto completions.

# Should this go to zlogin file?
if command -v tmux > /dev/null; then
  if [ -z "$TMUX" ]; then
    exec tmux new-session;
    exit;
  else
    [[ -v TMUX_OPEN_PROJECT ]] && proj --change-tmux-window-name --project "$(tmux display-message -p '#{window_name}')"
  fi
fi