. "$ZDOTDIR/config.zsh"    # Load ZSH and Interactive Shell Configuration.
. "$ZDOTDIR/plugins.zsh"   # Load Plugins.

# Load Functions - Lazy autoload every file under $ZDOTDIR/functions
fpath=("$ZDOTDIR/functions" $fpath);
autoload -Uz $fpath[1]/*(.:t)

# Load Application specific modules
for module in $ZDOTDIR/modules/*.zsh; do
  . $module
done

. "$ZDOTDIR/aliases.zsh"                         # Load Aliases.
. "$ZDOTDIR/auto-completions.zsh"                # Load Auto completions.

# Load any local zshrc scripts if present.
[ -s "$HOME"/.zshrc.local ] && source "$HOME"/.zshrc.local

# Should this go to zlogin file?
if command -v tmux > /dev/null; then
  if [ -z "$TMUX" ]; then
    exec tmux new-session;
    exit;
  fi
fi
